project/urls.py
from django.contrib import admin
from django.urls import path, include

from xml.dom.minidom import Document
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("shop.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("view/Shop/Service", views.view_shop, name="view_shop"),
    path("add/Shop/Service", views.add_service, name="add_service"),
    path("update/Shop/Service/<int:pk>", views.update_service, name="update_service"),
    path("delete/Shop/Service/<int:pk>", views.delete_service, name="delete_service"),
    path("add/Shop/Accessories/", views.add_accessories, name="add_accessories"),
    path(
        "update/Shop/Accessories/<int:pk>",
        views.update_accessories,
        name="update_accessories",
    ),
    path(
        "delete/Shop/Accessories/<int:pk>",
        views.delete_accessories,
        name="delete_accessories",
    ),
    # food
    path("add/Shop/Food", views.add_food, name="add_food"),
    path("update/Shop/Food/<int:pk>", views.update_food, name="update_food"),
    path("delete/Shop/Food/<int:pk>", views.delete_food, name="delete_food"),
    # checkupDoctors
    path(
        "view/checkup",
        views.DoctorsListView.as_view(),
        name="view_checkup_details",
    ),
    # page for admin view all tokens
    path(
        "view/Checkup/token",
        views.TokenListView.as_view(),
        name="view_tokens",
    ),
    # page for  admin view all service token
    path(
        "view/token/service",
        views.TokenServiceListView.as_view(),
        name="view_service_token",
    ),
    path(
        "add/Doctors/Checkup_details",
        views.add_doctors_checkup_details,
        name="add_doctors_checkup_details",
    ),
    path(
        "update/Doctors/Checkup_details/<int:pk>",
        views.update_doctors_checkup_details,
        name="update_doctors_checkup_details",
    ),
    path(
        "delete/Doctors/Checkup_details/<int:pk>",
        views.delete_doctors_checkup_details,
        name="delete_doctors_checkup_details",
    ),
    # checkupDoctors
    path(
        "add/Token/Checkup_details",
        views.add_token_checkup_details,
        name="add_token_checkup_details",
    ),
    path(
        "update/Token/Checkup_details/<int:pk>",
        views.update_token_checkup_details,
        name="update_token_checkup_details",
    ),
    path(
        "delete/Token/Checkup_details/<int:pk>",
        views.delete_token_checkup_details,
        name="delete_token_checkup_details",
    ),
    # Appointment for Checkup
    # all appointment in admin
    path(
        "view/Appointment/Booking",
        views.AppointmentListView.as_view(),
        name="view_appointment",
    ),
    path("Appointment/Booking", views.booking_appointment, name="booking_appointment"),
    # service booking Crud
    path(
        "Booking/ServiceOffered/<int:pk>",
        views.booking_service_offered,
        name="booking_service_offered",
    ),
    path(
        "update/Booking/Service Offered/<int:pk>",
        views.update_booking_service_offered,
        name="update_booking_service_offered",
    ),
    path(
        "delete/Booking/Service Offered/<int:pk>",
        views.delete_booking_service_offered,
        name="delete_booking_service_offered",
    ),
    # accessories booking CRUD
    path(
        "Booking/accessories/<int:pk>",
        views.booking_accessories,
        name="booking_accessories",
    ),
    path(
        "update/Booking/accessories/<int:pk>",
        views.update_booking_accessories,
        name="update_booking_accessories",
    ),
    path(
        "delete/Booking/accessories/<int:pk>",
        views.delete_booking_accessories,
        name="delete_booking_accessories",
    ),
    # food booking Crud
    path("Booking/Food/<int:pk>", views.booking_food, name="booking_food"),
    path(
        "update/Booking/food_items/<int:pk>",
        views.update_booking_food,
        name="update_booking_food",
    ),
    path(
        "delete/Booking/food_items/<int:pk>",
        views.delete_booking_food,
        name="delete_booking_food",
    ),
    # admin list for all booking
    path(
        "view/Booking/Service Offered",
        views.BookedServiceListView.as_view(),
        name="view_service_booking",
    ),
    path(
        "view/Booking/accessories",
        views.BookedAccessoriesListView.as_view(),
        name="view_accessories_booking",
    ),
    path(
        "view/Booking/food_products",
        views.BookedFoodListView.as_view(),
        name="view_food_booking",
    ),
    # service token
    path(
        "token/add/Service Offered",
        views.add_token_service_offered,
        name="add_token_service_offered",
    ),
    path(
        "token/update/Service Offered/<int:pk>",
        views.update_token_service_offered,
        name="update_token_service_offered",
    ),
    path(
        "token/delete/Service Offered/<int:pk>",
        views.delete_token_service_offered,
        name="delete_token_service_offered",
    ),
    # path("token/view/Service Offered", views.view_token_service_offered, name="view_token_service_offered"),
    # path("Booking/Accessories/<int:pk>", views.booking_accessories, name="booking_accessories"),
    # path("Booking/Accessories/<int:pk>", views.booking_accessories, name="booking_accessories"),
    # Checkup for user EDIT/DELETE
    # path(
    #     "view/Booking/Appointment/",
    #     views.BookingAppointment.as_view(),
    #     name="user_booking_appointment",
    # ),
    # booking Appointment
    path(
        "edit/Appointment/Booking/<int:pk>",
        views.update_appointment,
        name="update_appointment",
    ),
    path(
        "delete/Appointment/Booking/<int:pk>",
        views.delete_appointment,
        name="delete_appointment",
    ),
    # checkup for admin Update
    path(
        "status/Appointment/Booking/<int:pk>",
        views.status_appointment,
        name="status_appointment",
    ),
    # booking item in  dashboard food and accesories
    path("booking/service", views.BookedService.as_view(), name="booked_service"),
    path(
        "booking/accessories",
        views.BookedAccessories.as_view(),
        name="booked_accessories",
    ),
    path("booking/food", views.BookedFood.as_view(), name="booked_food"),
    # status
    path(
        "booking/status/food/<int:pk>",
        views.StatusBookedFood.as_view(),
        name="status_booked_food",
    ),
    path(
        "booking/status/accessories/<int:pk>",
        views.StatusBookedAccessories.as_view(),
        name="status_booked_accessories",
    ),






    
    # list status
    path(
        "booking/status/food/<int:pk>",
        views.StatusBookedFood.as_view(),
        name="status_booked_food",
    ),
    path(
        "booking/status/accessories/",
        views.StatusBookedAccessoriesListView.as_view(),
        name="list_booked_accessories",
    ),
    path(
        "booking/status/food/",
        views.StatusBookedFoodListView.as_view(),
        name="list_booked_food",
    ),
]

shop/models.py
from django.db import models
from users.models import CustomUser
from django.core.exceptions import ValidationError
from phonenumber_field.modelfields import PhoneNumberField  # Use this for models

# Doggy Essentials
class ServiceOffered(models.Model):
    service_name = models.CharField(max_length=300)
    price = models.PositiveIntegerField()
    image = models.ImageField(upload_to="service_offered_image")
    phone=PhoneNumberField(blank=True)


    def __str__(self):
        return self.service_name


class Accessories(models.Model):
    total_stock = models.PositiveIntegerField(null=False, blank=False, default=1)

    accessories_name = models.CharField(max_length=300)
    image = models.ImageField(upload_to="Accessories")
    price = models.PositiveIntegerField()
    username = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, blank=True, null=True
    )

    def __str__(self):
        return self.accessories_name


class DogFood(models.Model):
    total_stock = models.PositiveIntegerField(null=True, blank=True, default=0)

    Food_name = models.CharField(max_length=300)
    image = models.ImageField(upload_to="Food")
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.Food_name


# token Service
class TokenService(models.Model):
    token = models.CharField(max_length=200, null=True, blank=True, unique=True)

    available = models.BooleanField(default=True, null=True, blank=True)

    def __str__(self):
        return self.token


# Booking Doggy Essentials
class BookingService(models.Model):
    service_name = models.ForeignKey(ServiceOffered, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    username = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=True, blank=True
    )
    token = models.ForeignKey(
        TokenService,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text="NB : Choose your Token based on Your service",
    )
    date = models.DateTimeField(auto_now=True, editable=False)


class BookingAccessories(models.Model):
    STATUS = (("delivered", "Delivered"), ("not delivered", "Not Delivered"))
    PAYEMENT = (
        ("COD", "Cash on Delivery"),
        ("ONLINE", "Online Payment"),
    )

    total_stock = models.ForeignKey(
        Accessories,
        on_delete=models.CASCADE,
        related_name="stocks",
        null=True,
        blank=True,
    )
    username = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=True, blank=True
    )
    quantity = models.PositiveIntegerField(
        null=False, blank=False
    )  # This makes the field required

    accessories_name = models.ForeignKey(
        Accessories, on_delete=models.CASCADE, null=True, blank=True
    )
    price = models.PositiveIntegerField(null=True, blank=True)
    total_price = models.PositiveIntegerField(null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    date = models.DateTimeField(auto_now=True, editable=False)
    payement_mode = models.CharField(
        max_length=200,
        choices=PAYEMENT,
        null=True,
        blank=True,
        help_text="NB : If you choose online payment, after completing the payment you need to click  confirm button otherwise order will not be placed",
    )
    status = models.CharField(max_length=200, choices=STATUS, null=True, blank=True,default="not delivered")

    def save(self, *args, **kwargs):
        self.total_price = self.price * self.quantity
        if self.quantity < 1:
            raise ValidationError("Quantity must be at least 1")
        if self.total_stock:
            # if self.total_stock.total_stock == 0:
            #     raise ValidationError("OUT OF STOCK")
            if self.total_stock.total_stock < self.quantity:
                raise ValidationError(
                    "Quantity must be less than or equal to available stock"
                )

        return super().save(*args, **kwargs)


class BookingFood(models.Model):
    STATUS = (("delivered", "Delivered"), ("not delivered", "Not Delivered"))

    PAYEMENT = (
        ("COD", "Cash on Delivery"),
        ("ONLINE", "Online Payment"),
    )

    Food_name = models.ForeignKey(DogFood, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(null=False, blank=False)
    total_stock = models.ForeignKey(
        DogFood, on_delete=models.CASCADE, related_name="stocks", null=True, blank=True
    )
    username = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, blank=True, null=True
    )
    total_price = models.PositiveIntegerField(blank=True, null=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    date = models.DateTimeField(auto_now=True, editable=False)
    status = models.CharField(max_length=200, choices=STATUS, null=True, blank=True,default="not delivered")

    payement_mode = models.CharField(
        max_length=200,
        choices=PAYEMENT,
        null=True,
        blank=True,
        help_text="NB : If you choose online payment, after completing the payment you need to click  'confirm booking' button to confirm order otherwise order will not be placed",
    )

    def save(self, *args, **kwargs):
        self.total_price = self.price * self.quantity
        if self.quantity < 1:
            raise ValidationError("quantity must be At least 1")
        if self.total_stock:

            if self.total_stock.total_stock < self.quantity:
                raise ValidationError(
                    "Quantity must be less than or equal to available stock"
                )

        return super().save(*args, **kwargs)


# Checkup Details DOctors Token And booking Appointment
class Doctors(models.Model):
    doctor_name = models.CharField(max_length=200, unique=True, blank=True)
    specialized = models.CharField(max_length=200, blank=True)
    availability = models.BooleanField(default=True)

    def __str__(self):
        return self.doctor_name


class Token(models.Model):
    Token = models.CharField(max_length=200, unique=True)

    token_available = models.BooleanField(default=True)

    def __str__(self):
        return self.Token


class TokenAvailability(models.Model):
    token = models.ForeignKey(Token, on_delete=models.CASCADE)
    date = models.DateField()
    is_available = models.BooleanField(
        default=True
    )  # Specific availability for this date

    class Meta:
        unique_together = ("token", "date")  # Ensure each token-date pair is unique

    def __str__(self):
        return f"{self.token} - {self.date} - {'Available' if self.is_available else 'Unavailable'}"


class Appointment(models.Model):
    # AVAILABE FIELD added for status
    STATUS = (
        ("confirm booking", "Confirm Booking"),
        (
            "finished",
            "Finished",
        ),
        ("pending", "Pending"),
    )
    username = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    doctor_name = models.ForeignKey(Doctors, on_delete=models.CASCADE)
    Token = models.ForeignKey(Token, on_delete=models.CASCADE)
    status = models.CharField(max_length=200, choices=STATUS, default="pending")
    appointment_date = models.DateField()

shop/templates/all_service_tokens.html
{% extends "base.html" %}
{% block content %}
    {% if request.user.role == "SHOP OWNER" %}
        <div class="container ">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb fs-4">
                    <li class="breadcrumb-item">
                        <a href="{% url 'home' %}" class="text-decoration-none text-black"><i class="bi bi-house-door-fill"></i></a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">{{ page_title }}</li>
                </ol>
            </nav>
        </div>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end me-4 mt-2">
            <a href="{% url 'add_doctors_checkup_details' %}">
                <button class="btn btn-primary me-md-2 btn-sm mt-2" type="button">Add Doctors</button>
            </a>
            <a href="{% url 'add_token_checkup_details' %}">
                <button class="btn btn-primary btn-sm mt-2" type="button">Add Tokens</button>
            </a>
            <a href="{% url 'view_tokens' %}">
                <button class="btn btn-primary me-md-2 btn-sm mt-2" type="button">Checkup Token Details</button>
            </a>
            <a href="{% url 'view_checkup_details' %}">
                <button class="btn btn-primary btn-sm mt-2" type="button">All Doctors Details</button>
            </a>
        </div>
        <div class="container mt-4">
            {% if all_tokens_services %}
                <h5 class="text-center">Service Token Details</h5>
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover">
                        <thead>
                            <tr class="text-center">
                                <th>Token</th>
                                <th colspan=2>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for all_tokens_service in all_tokens_services %}
                                <tr class="text-center">
                                    <td>{{ all_tokens_service.token }}</td>
                                    <td>
                                        <a href="{% url 'update_token_service_offered' all_tokens_service.id %}">
                                            <button type="submit" class="btn btn-success btn-sm">Update</button>
                                        </a>
                                    </td>
                                    <td>
                                        <button type="button"
                                                class="btn btn-danger btn-sm"
                                                data-bs-toggle="modal"
                                                data-bs-target="#exampleModal{{ all_token.id }}">Delete</button>
                                    </td>
                                </tr>
                                <!-- Modal -->
                                <div class="modal fade"
                                     id="exampleModal{{ all_token.id }}"
                                     tabindex="-1"
                                     aria-labelledby="exampleModal{{ all_token.id }}"
                                     aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="exampleModal{{ all_token.id }}">Delete</h1>
                                                <button type="button"
                                                        class="btn-close"
                                                        data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">Are You Sure You Want to Delete</div>
                                            <div class="modal-footer">
                                                {% comment %} <a href="{% url 'delete_token_checkup_details' all_token.id %}"> {% endcomment %}
                                                <button type="button" class="btn btn-Danger btn-sm">Confirm Delete</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </tbody>
                </table>
                {% include "pagination.html" %}
            </div>
        {% else %}
            <div class="alert alert-primary text-center" role="alert">Currently No Tokens Added</div>
        {% endif %}
    </div>
{% endif %}
{% endblock content %}

shop/templates/booking_dog_care.html
{% extends "base.html" %}
{% block content %}
    <div class="container ms-2">
        <nav class="breadcrumb">
            <ol class="breadcrumb fs-4">
                <li class="breadcrumb-item">
                    <a href="{% url 'home' %}" class="text-decoration-none text-black"><i class="bi bi-house-door-fill"></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">{{ page_title }}</li>
            </ol>
        </nav>
    </div>
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% if accessories %}
                                <div>
                                    <label>Accessories name:</label>
                                    {{ form.accessories_name }}
                                    <br>
                                    <label>Price:</label>
                                    {{ form.price }}
                                    <br>
                                    <label>Quantity:</label>
                                    {{ form.quantity }}
                                    <br>
                                    <br>
                                    <label>Address:</label>
                                    {{ form.address }}
                                    <br>
                                    <br>
                                    <label>Email:</label>
                                    {{ form.email }}
                                    <br>
                                    <br>
                                    <label>Payment Mode:</label>
                                    <select name="payement_mode" class="form-control" id="id_payement_mode">
                                        <option value="" selected>---------</option>
                                        <option value="COD">Cash on Delivery</option>
                                        <option value="ONLINE">Online Payment</option>
                                    </select>
                                    <small class="form-text text-danger">{{ form.payement_mode.help_text }}</small>
                                    <br>
                                    <div class="d-flex justify-content-center mt-4">
                                        <div class="d-inline-flex gap-1">
                                    <p class="text-center text-success">
                                        Total price: <span id="total_price">0</span>
                                    </p>
                                |
                                    <p class="text-center text-success">
                                        Total Stock: <span id="total_stock">{{ all_accessorie.total_stock }}</span>
                                    </p>
                                </div>
                            </div>
                                </div>
                            {% endif %}
                            {% if food %}
                                <label>Food Product:</label>
                                {{ form.Food_name }}
                                <br>
                                <label>Price:</label>
                                {{ form.price }}
                                <br>
                                <label>Quantity:</label>
                                {{ form.quantity }}
                                <br>
                                <label>Address:</label>
                                {{ form.address }}
                                <br>
                                <br>
                                <label>Email:</label>
                                {{ form.email }}
                                <br>
                                <br>
                                <label>Payment Mode:</label>
                                <select name="payement_mode" class="form-control" id="id_payement_mode">
                                    <option value="" selected>---------</option>
                                    <option value="COD">Cash on Delivery</option>
                                    <option value="ONLINE">Online Payment</option>
                                </select>
                                <small class="form-text text-danger">{{ form.payement_mode.help_text }}</small>
                                <br>
                                <div class="d-flex justify-content-center mt-4">
                                    <div class="d-inline-flex gap-1">
                                        <p class="text-center text-success">
                                            Total price: <span id="total_price">0</span>
                                        </p>
                                        |
                                        <p class="text-center text-success">Total Stock : {{ all_food.total_stock|default:"0" }}</p>
                                    </div>
                                </div>
                            {% endif %}
                            {% csrf_token %}
                            <div class="d-flex justify-content-center mt-4">
                                <button type="submit" class="btn btn-primary btn-sm ">Confirm Booking</button>
                            </form>
                            <!-- Pay button that will only appear if payment mode is 'ONLINE' -->
                            <button id="rzp-button1"
                                    class="btn btn-success btn-sm ms-2"
                                    style="display:none">Pay With Razorpay</button>
                        </div>
                        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
                        <script>
                        // Function to calculate total price
                        function calculateTotalPrice() {
                            let price = parseFloat(document.getElementById('id_price').value) || 0;
                            let quantity = parseFloat(document.getElementById('id_quantity').value) || 0;

                            // Calculate the total price
                            let totalPrice = price * quantity;

                            // Update the total price display, fallback to 0 if NaN
                            document.getElementById('total_price').textContent = isNaN(totalPrice) ? "0" : totalPrice.toFixed(2);

                            // Update Razorpay amount
                            return totalPrice;
                        }

                        // Event listeners for input fields to update the total price
                        document.getElementById('id_price').addEventListener('input', calculateTotalPrice);
                        document.getElementById('id_quantity').addEventListener('input', calculateTotalPrice);

                        // Function to show/hide the Pay button based on Payment Mode
                        function togglePayButton() {
                            let paymentMode = document.getElementById('id_payement_mode').value;
                            let payButton = document.getElementById('rzp-button1');

                            if (paymentMode === 'ONLINE') {
                                payButton.style.display = 'block';  // Show Pay button
                            } else {
                                payButton.style.display = 'none';   // Hide Pay button
                            }
                        }

                        // Trigger the toggle function on page load and when the payment mode changes
                        document.getElementById('id_payement_mode').addEventListener('change', togglePayButton);

                        // Initial check when the page loads
                        togglePayButton();

                        // Razorpay payment options with dynamic amount
                        document.getElementById('rzp-button1').onclick = function(e) {
                            // Get the dynamic total price
                            let totalPrice = calculateTotalPrice();

                            // Validate all required fields
                            let isValid = true;
                            let requiredFields = [
                                'id_price', 'id_quantity', 'id_address', 'id_email', 'id_payement_mode'
                            ];

                            // Loop through each field and check if it has a value
                            for (let fieldId of requiredFields) {
                                let field = document.getElementById(fieldId);
                                if (!field) {
                                    // If the field does not exist, continue with next iteration
                                    continue;
                                }

                                // Check for empty input fields or invalid values
                                if (field.value.trim() === "") {
                                    isValid = false;
                                    break;
                                }

                                // Special case for dropdown fields (like payment_mode) if applicable
                                if (field.tagName === "SELECT" && field.value === "") {
                                    isValid = false;
                                    break;
                                }
                            }

                            // Show alert if the form is not valid
                            if (!isValid) {
                                Swal.fire({
                                    title: "Warning",
                                    text: "All fields are required",
                                    icon: "warning",
                                  });
                                 e.preventDefault();
                                return;
                            }

                            // Razorpay payment options with dynamic amount
                            var options = {
                                "key": "rzp_test_bExXeTSGdRlunx", // Enter the Key ID generated from the Dashboard
                                "amount": (totalPrice * 100).toFixed(0), // Amount in paise (multiplying by 100)
                                "currency": "INR",
                                "name": "HEY DOGGY!!@Authority", // Your business name
                                "description": "HEY DOGGY!!",
                                "image": "https://example.com/your_logo",
                                "order_id": "{{ payment.id }}", // This is a sample Order ID. Pass the `id` obtained in the response of Step 1
                                "prefill": {
                                    "name": "Gaurav Kumar", // Your customer's name
                                    "email": "gaurav.kumar@example.com",
                                    "contact": "9000090000" // Provide the customer's phone number for better conversion rates
                                },
                                "notes": {
                                    "address": "Razorpay Corporate Office"
                                },
                                "theme": {
                                    "color": "red"
                                }
                            };

                            var rzp1 = new Razorpay(options);
                            rzp1.open();
                            e.preventDefault();
                        }
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}